os:
  - linux

dist: xenial

language: php

php:
  - '7.3'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

before_script:
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - cp .env.travis .env
  - phpenv rehash
  - nvm install 10.11.0
  - npm install npm@latest -g
  - npm install -g eslint eslint-plugin-react
  - npm install
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - eslint resources/js/*
